DOCUMENT_LEVEL = 0
TOP_HEADING_LEVEL = 1
MAX_HEADING_LEVEL = 6
DEFAULT_ROOT_TITLE = "Document"
CODE_FENCE_DELIMITER = "```"
BLANK_CHAR = " "
NEWLINE = "\n"

HEADING_GROUP_HASHES = "hashes"
HEADING_GROUP_TITLE = "title"

FRAME_KEY_LEVEL = "level"
FRAME_KEY_TITLE = "title"
FRAME_KEY_CONTENT = "content"
FRAME_KEY_CHILDREN = "children"

PATH_SEPARATOR = "/"
CHUNK_PATH_PREFIX = "chunk_"
PART_TITLE_SEPARATOR = " — Part "
SLUG_SEPARATOR = "_"
DEFAULT_SLUG = "section"
SLUG_PATTERN = r"[^a-z0-9]+"
DEFAULT_UNTITLED_DOCUMENT_TITLE = "Untitled Document"

MAX_CHUNKS_PER_DOC = 20
SIMILARITY_THRESHOLD = 0.45
MAX_TOKENS_PER_CHUNK = 350
MIN_TOKENS_PER_CHUNK = 80
TOKENS_PER_WORD_RATIO = 0.75
MIN_TOKEN_ESTIMATE = 10

DEFAULT_FIXED_CHUNK_SIZE = 350
DEFAULT_FIXED_CHUNK_OVERLAP = 50

MONOTONOUS_SIMILARITY_THRESHOLD = 0.8
FULL_COHERENCE = 1.0
COSINE_EPSILON = 1e-9
SPACY_LANGUAGE = "en"
SPACY_SENTENCIZER_PIPE = "sentencizer"
SENTENCE_BOUNDARY_PATTERN = r"(?<=[.!?])\s+"

GROUP_KEY_SENTENCES = "sentences"
GROUP_KEY_EMBEDDINGS = "embeddings"
GROUP_KEY_CENTROID = "centroid"

PARAGRAPH_SIMILARITY_THRESHOLD = 0.55
PARAGRAPH_BOUNDARY_PATTERN = r"\n\s*\n"
